# Site
name: "Mix the World"
title: "Mix the World"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-xxxxxxxx-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mario:
    name: Mario Viapiano
    display_name: mviapiano
    avatar: 'assets/images/avatar-sal.png'
    email: mario@mixthe.world
    twitter: https://twitter.com/mariiillo
    description: "Hi! I'm Mario"
  paula:
    name: Paula van Belkom
    display_name: paula.vanbelkom
    avatar: 'assets/images/avatar.png'
    email: paula@mixthe.world
    twitter: ''
    description: "Hi! I'm Paula"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
